version: "3"
services:
  server:
    image: blog_app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/news?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=news
      - MYSQL_USER=admin_blog
      - MYSQL_PASSWORD=adm_blog_adm

networks:
  springmysql-net: