version: "3"
services:
  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  server:
    image: blog_app:v1
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/news?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb
networks:
  springmysql-net: